import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://127.0.0.1:8000/timetracker/login');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('Administrator');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('123');
  await page.getByRole('textbox', { name: 'Password' }).press('Enter');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('textbox', { name: 'Enter ID' }).click();
  await page.getByRole('textbox', { name: 'Enter ID' }).fill('12');
  await page.getByRole('button', { name: 'Clock In Record your arrival' }).click();
  await page.getByRole('button', { name: 'Factory Cleaning Record' }).click();
  await page.getByRole('textbox', { name: 'Enter ID' }).fill('12');
  await page.getByRole('button', { name: 'Start Job Begin working on a' }).click();
  await page.getByRole('button', { name: 'Machine SO Number: SO-0122' }).click();
  await page.getByRole('textbox', { name: 'Enter ID' }).fill('12');
  await page.getByRole('button', { name: 'Start Job Begin working on a' }).click();
  await expect(page.getByRole('button', { name: 'Mark Complete', exact: true })).toBeVisible();
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('button', { name: 'Start Job Begin working on a' }).click();
  await page.getByRole('textbox', { name: 'Search jobs by operation,' }).click();
  await page.getByRole('textbox', { name: 'Search jobs by operation,' }).fill('pre');
  await page.getByRole('button', { name: 'PreFinish SO Number: SO-0049 Job ID: PO-JOB00227 Item: Tiimber Panel Customer:' }).click();
  await page.getByRole('textbox', { name: 'Enter ID' }).fill('12');
  await expect(page.getByText('Currently working on: PO-')).toBeVisible();
  await page.getByRole('button', { name: 'Break Take a short break' }).click();
  await page.getByRole('textbox', { name: 'Enter ID' }).fill('12');
  await page.getByRole('button', { name: 'End Break Resume working on' }).click();
  await page.getByRole('textbox', { name: 'Enter ID' }).fill('12');
  await page.getByRole('button', { name: 'Start Job Begin working on a' }).click();
  await page.getByRole('button', { name: 'Machine SO Number: SO-0122' }).click();
  await page.getByRole('textbox', { name: 'Enter ID' }).fill('12');
  await page.getByRole('button', { name: 'Start Job Begin working on a' }).click();
  await page.getByRole('button', { name: 'Tasks' }).click();
  await page.getByRole('button', { name: 'SO-0096 Jon Wilson SO Number' }).click();
  await page.getByRole('textbox', { name: 'Enter ID' }).fill('12');
  await page.getByRole('button', { name: 'Lunch Take a lunch break' }).click();
  await page.getByRole('textbox', { name: 'Enter ID' }).fill('12');
  await page.getByRole('button', { name: 'End Lunch Resume Task: SO-' }).click();
  await page.getByRole('textbox', { name: 'Enter ID' }).fill('12');
  await page.getByRole('button', { name: 'Production Planning Start' }).click();
  await page.getByRole('textbox', { name: 'Enter ID' }).fill('12');
  await page.getByRole('button', { name: 'Start Job Begin working on a' }).click();
  await page.getByRole('button', { name: 'Tasks' }).click();
  await page.getByRole('button', { name: 'Real Interior NZ SO-0085 SO' }).click();
  await page.getByRole('textbox', { name: 'Enter ID' }).fill('12');
  await page.getByRole('button', { name: 'Clock Out Record your' }).click();
});